// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sixpcrgvsxfhtthwdbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeHBjcmd2c3hmaHR0aHdkYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDE4MjMsImV4cCI6MjA3MDUxNzgyM30.QWCqVAQvWZZBbyjL7OUTQV8mWxc8rHvaAaN3OYOZtec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});