name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy via FTP/FTPS/SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          protocol: ${{ secrets.HOSTINGER_FTP_PROTOCOL || 'ftps' }} # options: ftp, ftps, sftp
          port: ${{ secrets.HOSTINGER_FTP_PORT || 21 }}
          server-dir: ${{ secrets.HOSTINGER_FTP_SERVER_DIR }} # e.g. /domains/boards.zoby.ai/public_html/
          local-dir: dist
          log-level: standard
          # Uncomment to wipe target before upload
          # dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/public/**